// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uibbfgmtvbdrkuhbmljf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpYmJmZ210dmJkcmt1aGJtbGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDQwOTQsImV4cCI6MjA2MTQ4MDA5NH0.NNsE6XpglT42YcdS8NO7FHG04kRSDsA4cwXXJi8pav0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);